version: '3.6'

services:

    site: 
        image: node:lts-alpine
        container_name: site
        command: cd /site/ && npm install && npm start
        volumes:
            - ./site:/site
        ports:
            - 3000:3000